/*  -------------------------------------- USUÁRIOS - ALUNOS -------------------------------------- */
INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('GILSON.ALMEIDA', 'G1501375')

INSERT INTO USUARIO (LOGIN , SENHA) VALUES
('SEBASTIAO.RODRIGUES','S1602440') 

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('VALDIR.CASTRO', 'V1602396')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('LUIZ.MELO', 'L1701777')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('FRASNCISCO.JESUS', 'F1602405')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('NELSO.MOREIRA', 'N1602128')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('RAIMUNDO.MORAES', 'R1602230')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('FABIO.MOURA', 'F1601249')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ANDRE.COSTA', 'A1701595')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARCIO.BATISRA', 'M1601576')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('VINICIUS.CONCEICAO', 'V8151650')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JAO.SOUZA', 'J1702249')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ANTONIO.MAGALHAES', 'A1702249')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JOSE.MORAIS', 'J1501148')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JONATHAN.FILHO', 'J1501148')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('PAULO.MELO', 'P1602770')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALESSANDRO.DIAS', 'A6026997')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EVERTON.MARTINS', 'E1602173')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EDSON.FERNANDES', 'E1601713')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EMERSON.MENEZES', 'E1602326')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('CICIERO.SANTANA', 'C1012157')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MICHELE.GARCIA', 'M1501464')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('DOUGLAS.XAVIER', 'D1502465')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('RODRIGO.GOMES', 'R1502808')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALEXANDRE.DIAS', 'A1601975')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MAURO.CARVALHO', 'M1702530')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EDUARDO.VIEIRA', 'E1602305')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('FABRICIO.MACHADO', 'F1701582')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('DANIEL.ROCHA', 'D1501352')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JEAN.NEVES', 'J1701910')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('TAMIRES.CAVALCANTE', 'T1701166')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('DIEGO.NETO', 'D1502850')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARCELO.SANTOS', 'M1602346')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('LEONARDO.CUNHA', 'L1601418')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALAN.AGUIAR', 'A1702476')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ADRIANA.MACHADO', 'A1702619')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARIA.NASCIMENTO', 'M1502116')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ANA.FARIAS', 'A1702648')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('RENATA.COSTA', 'R1702436')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('VERA.CARDOS', 'V1602388')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ELIANE.MENDES', 'E1701548')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JESSICA.PEREIRA', 'J1502514')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('PRISCILA.FARRIAS', 'P1601584')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ROSANGELA.RIBEIRO', 'R1502845')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('LUCIANA.FERREIRA', 'L1601609')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ELIANE.BRAGA', 'E1702717')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ANTONIA.FILHO', 'A1602719')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('PATRICIA.MORAIS', 'P1601963')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARIA.MORAIS', 'M1602611')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('CLAUDIA.MOURA', 'C1600144')

/*  -------------------------------------- USUÁRIOS - PROFESSORES -------------------------------------- */

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALAN.OLIVEIRA', 'A1501375')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALBERTO.JUNIOR', 'A1305375')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALEXANDRE.RANGEL', 'A1501475')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALEXANDRE.MARTINS', 'A1597675')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALVARO.TAKEI', 'A3451375')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ANA.SANTOS', 'A1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('BRUNO.KALKEVICIUS', 'B1531775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('CEZAR.BELLINI', 'C1593775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EDSON.SILVA', 'E1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EDSON.TSUKIMOTO', 'E1383795')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EDUARDO.QUEIROZ', 'E1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EMILIO.RESENDE', 'E1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('FELIPE.DIAS', 'F1580775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('FERNANDO.ZUHER', 'F1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('FRANCESCA.ROMANELLI', 'F1123775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('GISELDA.PEREIRA', 'G1583985')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('GUILHERME.LOHMANN', 'G1512775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('GUSTAVO.FERREIRA', 'G1343775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ILANA.CONCILIO', 'I1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ISA.MELAO', 'I1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JOAO.COUTINHO', 'J1583345')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JOSE.PRADO', 'J1509775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('LEONARDO.TAKUNO', 'L3583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('LUCAS.GONÇALVES', 'L1683775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('LUCIANO.CROCCO', 'L1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARCEL.PIRES', 'P1580775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARCELO.SILVA', 'M8983775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARCELO.TERRA', 'M1582075')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARCO.JEUNON', 'M1594775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('OSVALDO.TAKAI', 'O1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('PEDRO.PRADO', 'P1593774')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('PLINIO.FILHO', 'P1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('RENATO.SANTOS', 'R1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('RODRIGO.PIASSI', 'R1843775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('SERGIO.BRUZETTI', 'S1093775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('VANDERSON.BOSSI', 'V1589475')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('VICTOR.OLIVEIRA', 'V1553775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('VLADIMIR.CHAGAS', 'V1583775')

<<<<<<< HEAD
/*  -------------------------------------- USUÁRIOS - COORDENADORES -------------------------------------- */

INSERT INTO USUARIO (LOGIN, SENHA) VALUES ('BRUNO.LIMA','B1234567')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES ('ALAN.CARVALHO','A1234567')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES ('AYAO.OKAMOTO','Y1234567')

/*  -------------------------------------- TABELA ALUNO -------------------------------------- */

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(1, 'GILSON FERNANDES ALMEIDA','gf_almeida@impacta.com.br',
'11987654321','1501375')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(2, 'SEBASTIAO DE OLOVEIRA RODRIGUES ','sd_rodrigues@impacta.com.br',
'11912123890','1602440')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(3, 'VALDIR GOMES DE CASTRO','vg_castro@impacta.com.br',
'11356890235','1602396')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(4, 'LUIZ CARLOS DE JESUS MELO','id_melo@impacta.com.br',
'11957901238','1701777')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(5, 'FRASCISCO DE SOUZA JESUS','fd_jesus@impacta.com.br',
'11902367891','1602405')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(6, 'NELSO FERREIRA DE MOREIRA','nf_moreira@impacta.com.br',
'11912243571','1602128')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(7, 'RAIMUNDO VIEIRA MORAIS','rv_morais@faculdadeimpacta.com.br',
'11910786230','1602230')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(8, 'FABIO FERNANDES MOURA','FF_MOURA@impacta.com.br',
'11936891507','1601249')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(9, 'ANDRE SANTOS DE COSTA','AS_COSTA@impacta.com.br',
'11927890125','1701595')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(10, 'MARCIO DA COSTA BATISTA','MD_BATISTA_@impacta.com.br',
'1195634589','1601576')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(11, 'VINICIUS SOUZA CONCEICAO','vs_conceicao@impacta.com.br',
'1199781233','1501650')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(12, 'JOAO BATISTA ALVES DA SOUSA','ja_sousa@impacta.com.br',
'1191896542','1702249')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(13, 'ANTONIO CARLOS FERREIRA DE MAGALHAES','af_magalhaes@impacta.com.br',
'1197892347','1702525')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(14, 'JOSE CARLOS LIMA MORAIS','jl_morais@impacta.com.br',
'11967763450','1501148')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(15, 'JONATHAN SANTOS DE FILHO','js_filho@impacta.com.br',
'11978906541','1502810')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(16, 'PAULO RODRIGUES DA MELO','pr_melo@impacta.com.br',
'11978923442','1602770')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(17, 'ALESSANDRO  DIAS','a_dias@impacta.com.br',
'11978973451','1602697')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(18, 'EVERTON DE OLIVEIRA MARTINS','ed_martins@impacta.com.br',
'11928906541','1602173')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(19, 'EDSON APARECIDA DE FERNANDES','ea_fernandes@impacta.com.br',
'11976809567','1601713')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(20, 'EMERSON GOMES MENEZES','eg_menezes@impacta.com.br',
'11978645672','1602326')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(21, 'CICERO PEREIRA DE SANTANA','cp_santana@impacta.com.br',
'11967823659','1501257')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(22, 'MICHELE SOUZA GARCIA','ms_garcia@impacta.com.br',
'11985671264','1501464')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(23, 'DOUGLAS GONCALVES XAVIER','dg_xavier@impacta.com.br',
'11979128964','1502465')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(24, 'RODRIGO REGINA GOMES','rr_gomes@impacta.com.br',
'11978978971','1502808')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(25, 'ALEXANDRE DE JESUS DIAS','ad_dias@impacta.com.br',
'11925678901','1601975')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(26, 'MAURO DE JESUS CARVALHO','md_carvalho@impacta.com.br',
'11956783201','1702530')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(27, 'EDUARDO  VIEIR','e_vieira@impacta.com.br',
'11987123008','1602305')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(28, 'FABRICIO REGINA MACHADO','fr_machado@impacta.com.br',
'11919087655','1701582')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(29, 'DANIEL FERREIRA DE ROCHA','df_rocha@impacta.com.br',
'11919087644','1501352')


INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(30, 'JEAN DA COSTA NEVES','jd_neves@impacta.com.br',
'11919081155','1701910')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(31, 'TAMIRES PEREIRA DE CAVALCANTE','tp_cavalcante@impacta.com.br',
'11934570128','1701166')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(32, 'DIEGO REGINA NETO','dr_neto@impacta.com.br',
'11912222222','1502850')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(33, 'MARCELO DOS SANTOS','md_santos@impacta.com.br',
'11911111111','1602346')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(34, 'LEONARDO RODRIGUES DE CUNHA','lr_cunha@impacta.com.br',
'11912121212','1601418')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(35, 'ALAN ALVES AGUIAR','aa_aguiar@impacta.com.br',
'11919999999','1702476')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(36, 'ADRIANA FERNANDES MACHADO','af_machado@impacta.com.br',
'11989899898','1702619')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(37, 'MARIA BARBOSA NASCIMENTO','mb_nascimento@impacta.com.br',
'11934343434','1502116')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(38, 'ANA PAULA FERREIRA DE FARIAS','af_farias@impacta.com.br',
'11921212121','1702648')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(39, 'RENATA VIEIRA COSTA','rv_costa@impacta.com.br',
'11912312367','1702436')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(40, 'VERA  CARDOSO','v_cardoso@impacta.com.br',
'11987667887','1602388')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(41, 'ELIANE BARBOSA MENDES','eb_mendes@impacta.com.br',
'11935712900','1701548')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(42, 'JESSICA DE OLIVEIRA PEREIRA','jd_pereira@impacta.com.br',
'11920085679','1502514')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(43, 'PRISCILA MARIA DE FARIAS','pm_farias@impacta.com.br',
'11936789096','1601584')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(44, 'ROSANGELA PEREIRA DE RIBEIRO','rp_ribeiro@impacta.com.br',
'11902981236','1502845')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(45, 'LUCIANA MARIA FERREIRA','lm_ferreira@impacta.com.br',
'11900446688','1601609')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(46, 'ELAINE SOARES BRAGA','es_braga@impacta.com.br',
'11901010101','1702717')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(47, 'ANTONIA FERREIRA FILHO','af_filho@impacta.com.br',
'11902102101','1602719')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(48, 'PATRICIA DE SOUZA MORAIS','pd_morais@impacta.com.br',
'11904050609','1601963')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(49, 'MARIA JOSE APARECIDA MORAES','ma_moraes@impacta.com.br',
'11910904070','1602611')

INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR, RA) VALUES 
(50, 'CLAUDIA DE LIMA MOURA','cd_moura@impacta.com.br',
'11910809075','1601449')
 
 INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(51, 'ALAN ALVES DE OLIVEIRA', 'aa_oliveira@impacta.com.br','11987654321','ALAN')

 INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(52, 'ALBERTO DE MEDEIROS JUNIOR', 'am_junior@impacta.com.br','11976534321','ALBERTO')

/*  -------------------------------------- TABELA PROFESSOR -------------------------------------- */

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(53, 'ALEXANDRE LEITE RANGEL', 'al_rangel@impacta.com.br','11937654321','RANGEL')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(54, 'ALEXANDRE LOCCI MARTINS', 'al_martins@impacta.com.br','11987658221','MARTINS')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(55, 'ALVARO TOSHIO TAKEI', 'at_takei@impacta.com.br','11932654321','ALVARO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(56, 'ANA CRISTINA DOS SANTOS', 'ac_santos@impacta.com.br','11939854321','ANA')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(57, 'BRUNO ROBERTO KALKEVICIUS', 'br_kalkevicius@impacta.com.br','11939854021','BRUNO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(58, 'CEZAR BELLINI', 'c_bellini@impacta.com.br','11999804021','CEZAR')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(59, 'EDSON BENITES SILVA', 'eb_silva@impacta.com.br','11950854021','EDSON')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(60, 'EDSON TIHARU TSUKIMOTO', 'et_tsukimoto@impacta.com.br','11950684021','TSUKIMOTO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(61, 'EDUARDO LUIS DE QUEIROZ', 'el_queiroz@impacta.com.br','11950630421','EDU')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(62, 'EMILIO MURTA RESENDE', 'em_resende@impacta.com.br','11950844021','EMILIO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(63, 'FELIPE AUGUSTO ROCHA DIAS', 'fa_dias@impacta.com.br','11950575051','FELIPE')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(64, 'FERNANDO ZUHER', 'f_zuher@impacta.com.br','11950520481','FERNANDO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(65, 'FRANCESCA ROMANELLI', 'f_romanelli@impacta.com.br','11950862021','FRANCESCA')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(66, 'GISELDA FERNANDA PEREIRA', 'gf_pereira@impacta.com.br','11985254021','GISELDA')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(67, 'GUILHERME GARCEZ LOHMANN', 'gg_lohmann@impacta.com.br','11950885021','GUILHERME')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(68, 'GUSTAVO MENDES FERREIRA', 'gm_ferreira@impacta.com.br','11950852621','FERREIRA')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(69, 'ILANA DE ALMEIDA SOUZA CONCILIO', 'ia_concilio@impacta.com.br','11950201821','ILANA')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(70, 'IZA MELÃO', 'i_melão@impacta.com.br','11950000021','IZA')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(71, 'JOÃO PAULO VENÂNCIO COUTINHO', 'jp_coutinho@impacta.com.br','11952040021','JP')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(72, 'JOSÉ PACHECO DE ALMEIDA PRADO', 'jp_prado@impacta.com.br','11950285021','PACHECO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(73, 'LEONARDO MASSAYUKI TAKUNO', 'lm_takuno@impacta.com.br','11950008821','TAKUNO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(74, 'LUCAS MENDES MARQUES GONÇALVES', 'lm_gonçalves@impacta.com.br','11950257521','LUCAS')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(75, 'LUCIANO CROCCO', 'l_crocco@impacta.com.br','11950280021','LUCIANO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(76, 'MARCEL GINOTTI PIRES', 'mg_pires@impacta.com.br','11955550021','NARCEL')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(77, 'MARCELO CORREIA DA SILVA', 'mc_silva@impacta.com.br','11959900021','MARCELO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(78, 'MARCELO SANSINI TERRA', 'ms_terra@impacta.com.br','11950882021','SANSINI')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(79, 'MARCO TÚLIO JEUNON', 'mt_jeunon@impacta.com.br','11958530021','MARCO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(80, 'OSVALDO KOTARO TAKAI', 'ok_takai@impacta.com.br','11950066021','TAKAI')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(81, 'PEDRO FELIPE DO PRADO', 'pf_prado@impacta.com.br','11950756021','PEDRO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(82, 'PLÍNIO BARBIERI FILHO', 'pb_filho@impacta.com.br','11950999021','PLINIO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(83, 'RENATO DE SOUZA SANTOS', 'rs_santos@impacta.com.br','11989626021','RENATO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(84, 'RODRIGO PIASSI', 'r_piassi@impacta.com.br','11951066021','RODRIGO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(85, 'SÉRGIO EDUARDO DI SANTORO BRUZETTI', 'se_bruzetti@impacta.com.br','11950095021','SERGIO')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(86, 'VANDERSON GOMES BOSSI', 'vg_bossi@impacta.com.br','11952066021','VANDERSON')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(87, 'VICTOR INACIO DE OLIVEIRA', 'vi_oliveira@impacta.com.br','11955206021','VICTOR')

INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(88, 'VLADIMIR CHAGAS', 'v_chagas@impacta.com.br','11950520721','VLADMIR')

/*  -------------------------------------- TABELA COORDENADOR -------------------------------------- */

INSERT INTO COORDENADOR (IDUSUARIO,NOME,EMAIL,CELULAR) 
VALUES (65 ,'FRANCESCA ROMANELLI','f_romanelli@impacta.com.br','11999999999')

INSERT INTO COORDENADOR (IDUSUARIO,NOME,EMAIL,CELULAR)
VALUES (56 ,'ANA CRISTINA DOS SANTOS','ac_santos@impacta.com.br','11988888888')

INSERT INTO COORDENADOR (IDUSUARIO,NOME,EMAIL,CELULAR) 
VALUES (89 ,'BRUNO LUIS SOARES DE LIMA','bl_lima@impacta.com.br','11977777777')

INSERT INTO COORDENADOR (IDUSUARIO,NOME,EMAIL,CELULAR) 
VALUES ( 80,'OSVALDO KOTARO TAKAI','ok_takai@impacta.com.br','11966666666')

INSERT INTO COORDENADOR (IDUSUARIO,NOME,EMAIL,CELULAR) 
VALUES (90 ,'ALAN HENRIQUE PARDO DE CARVALHO','ac_carvalho@impacta.com.br','11955555555')

INSERT INTO COORDENADOR (IDUSUARIO,NOME,EMAIL,CELULAR) 
VALUES (91 ,'AYAO OKAMOTO','ao_okamoto@impacta.com.br','11944444444')

/*  -------------------------------------- TABELA DISCIPLINA -------------------------------------- */


