INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('GILSON.ALMEIDA', 'G1501375')

INSERT INTO USUARIO (LOGIN , SENHA) VALUES
('SEBASTIAO.RODRIGUES','S1602440') 

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('VALDIR.CASTRO', 'V1602396')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('LUIZ.MELO', 'L1701777')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('FRASNCISCO.JESUS', 'F1602405')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('NELSO.MOREIRA', 'N1602128')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('RAIMUNDO.MORAES', 'R1602230')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('FABIO.MOURA', 'F1601249')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ANDRE.COSTA', 'A1701595')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARCIO.BATISRA', 'M1601576')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('VINICIUS.CONCEICAO', 'V8151650')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JAO.SOUZA', 'J1702249')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ANTONIO.MAGALHAES', 'A1702249')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JOSE.MORAIS', 'J1501148')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JONATHAN.FILHO', 'J1501148')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('PAULO.MELO', 'P1602770')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALESSANDRO.DIAS', 'A16026997')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EVERTON.MARTINS', 'E1602173')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EDSON.FERNANDES', 'E1601713')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EMERSON.MENEZES', 'E1602326')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('CICIERO.SANTANA', 'C15012157')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MICHELE.GARCIA', 'M1501464')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('DOUGLAS.XAVIER', 'D1502465')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('RODRIGO.GOMES', 'R1502808')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALEXANDRE.DIAS', 'A1601975')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MAURO.CARVALHO', 'M1702530')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EDUARDO.VIEIRA', 'E1602305')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('FABRICIO.MACHADO', 'F1701582')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('DANIEL.ROCHA', 'D1501352')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JEAN.NEVES', 'J1701910')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('TAMIRES.CAVALCANTE', 'T1701166')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('DIEGO.NETO', 'D1502850')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARCELO.SANTOS', 'M1602346')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('LEONARDO.CUNHA', 'L1601418')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALAN.AGUIAR', 'A1702476')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ADRIANA.MACHADO', 'A1702619')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARIA.NASCIMENTO', 'M1502116')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ANA.FARIAS', 'A1702648')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('RENATA.COSTA', '1702436')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('VERA.CARDOS', 'V1602388')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ELIANE.MENDES', 'E1701548')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JESSICA.PEREIRA', 'J1502514')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('PRISCILA.FARRIAS', 'P1601584')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ROSANGELA.RIBEIRO', 'R1502845')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('LUCIANA.FERREIRA', 'L1601609')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ELIANE.BRAGA', 'E1702717')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ANTONIA.FILHO', 'A1602719')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('PATRICIA.MORAIS', 'P1601963')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARIA.MORAIS', 'M1602611')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('CLAUDIA.MOURA', 'C16001449')

/* USUÁRIOS - PROFESSORES */

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALAN.OLIVEIRA', 'A1501375')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALBERTO.JUNIOR', 'A1305375')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALEXANDRE.RANGEL', 'A1501475')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALEXANDRE.MARTINS', 'A1597675')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ALVARO.TAKEI', 'A3451375')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ANA.SANTOS', 'A1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('BRUNO.KALKEVICIUS', 'B1531775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('CEZAR.BELLINI', 'C1593775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EDSON.SILVA', 'E1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EDSON.TSUKIMOTO', 'E1383795')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EDUARDO.QUEIROZ', 'E1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('EMILIO.RESENDE', 'E1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('FELIPE.DIAS', 'F1580775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('FERNANDO.ZUHER', 'F1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('FRANCESCA.ROMANELLI', 'F1123775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('GISELDA.PEREIRA', 'G1583985')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('GUILHERME.LOHMANN', 'G1512775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('GUSTAVO.FERREIRA', 'G1343775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ILANA.CONCILIO', 'I1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('ISA.MELAO', 'I1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JOAO.COUTINHO', 'J1583345')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('JOSE.PRADO', 'J1509775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('LEONARDO.TAKUNO', 'L3583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('LUCAS.GONÇALVES', 'L1683775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('LUCIANO.CROCCO', 'L1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARCEL.PIRES', 'P1580775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARCELO.SILVA', 'M8983775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARCELO.TERRA', 'M1582075')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('MARCO.JEUNON', 'M1594775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('OSVALDO.TAKAI', 'O1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('PEDRO.PRADO', 'P1593774')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('PLINIO.FILHO', 'P1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('RENATO.SANTOS', 'R1583775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('RODRIGO.PIASSI', 'R1843775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('SERGIO.BRUZETTI', 'S1093775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('VANDERSON.BOSSI', 'V1589475')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('VICTOR.OLIVEIRA', 'V1553775')

INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('VLADIMIR.CHAGAS', 'V1583775')




